<?php $environment = Mage::helper('borderfreesettings')->getEnvironment()?>
<div id="trackingContainer">
    <h3><strong>You need to upgrade your Adobe Flash Player</strong></h3>
 
    <a href="https://www.adobe.com/go/getflashplayer" target="getflashplayer">
        <img src=https://www.adobe.com/images/shared/download_buttons/get_flash_player.gif
         alt="Get Adobe Flash Player" width="88" height="31" border="0" />
 
        Download the free Adobe Flash Player now! </a>
    <p> If you have already installed the latest version of Adobe Flash Player and you
    still see this message then refer to your browser's documentation to learn how to enable JavaScript.</p>
</div>
 
<script type="text/JavaScript" src="https://<?php echo $environment?>.borderfree.com/tracking/swfobject.js"></script>
<script type="text/javascript">
 
    var ePath = "https://<?php echo $environment?>.borderfree.com/flex/tracking/tracking.swf";
    var eID = "flashOrderGeneralId";
    var eWidth = <?php echo Mage::helper('borderfreesettings')->getTrackHeight()?>;
    var eHeight = <?php echo Mage::helper('borderfreesettings')->getTrackHeight()?>;
    var fpMinVer = "9";
    var eBackground = "#FFFFFF";
    var so = new SWFObject(ePath, eID, eWidth, eHeight, fpMinVer, eBackground);
    so.setAttribute("AllowScriptAccess","always");
    so.useExpressInstall("https://$environment.borderfree.com/utils/expressinstall.swf");
    so.setAttribute("xiRedirectUrl",window.location);
    so.write("trackingContainer");
</script>